export 'package:auto_size_text/auto_size_text.dart';
export 'package:flutter/material.dart';
export 'package:hnhot/Repo/repo.dart';
// export 'package:flutter_animate/flutter_animate.dart';
// export 'package:flutter_bloc/flutter_bloc.dart';
// export 'package:flutter_paypal/flutter_paypal.dart';
// export 'package:fluttertoast/fluttertoast.dart';
// export 'package:google_fonts/google_fonts.dart';
// export 'package:google_sign_in/google_sign_in.dart';
// export 'package:lifecoach/Bloc/bloc.dart';
// export 'package:lifecoach/Model/model.dart';
// export 'package:lifecoach/Repo/repo.dart';
// export 'package:lifecoach/Routes/routes.dart';
// export 'package:lifecoach/Views/Auth/otp_screen.dart';
// export 'package:lifecoach/Views/My%20Notes/add_edit_notes.dart';
// export 'package:lifecoach/Views/My%20Notes/notes_search_screen.dart';
// export 'package:lifecoach/Views/views.dart';
export 'package:hnhot/Widgets/widget.dart';
export 'package:lottie/lottie.dart';

// export 'package:lottie/lottie.dart';
// export 'package:path_provider/path_provider.dart';
// export 'package:permission_handler/permission_handler.dart';
// export 'package:video_thumbnail/video_thumbnail.dart';
// export 'package:weekly_date_picker/weekly_date_picker.dart';
// export 'package:flutter/cupertino.dart';
export 'colors.dart';
export 'global.dart';

const String baseUrl = "http://lifecoachapi.synergic360.com/api";
